services:
  resource-server:
    build: ./resource-server
    environment:
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - ISSUER_URI=${ISSUER_URI}
    network_mode: host
  
  authorization-server:
    build: ./authorization-server
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - DB_PASSWORD=${DB_PASSWORD}
    network_mode: host

  ag-prueba-front:
    build: 
      context: ./ag-prueba-front
      args:
        - API_URL=${RESOURCE_URL}
    network_mode: host